Deploying Run migrations Job

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,24 +22,24 @@ commands:
             # Delete back end stack
             aws cloudformation delete-stack --stack-name udapeople-backend-${CIRCLE_WORKFLOW_ID}
 
-#   revert-migrations:
-#     description: Revert the last migration if successfully run in the current workflow.
-#     parameters:
-#       # Add parameter here     
-#     steps:
-#       - run:
-#           name: Revert migrations
-#           # Add when this will run
-#           command: |
-#             # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-#             SUCCESS = 1
-#             if(( $SUCCESS==1 )); 
-#             then
-#             #  cd ~/project/backend
-#             #  npm install
-#             #  Add revert code here. You can find this in the Getting Started section.
-#               exit 1
-#             fi
+  # revert-migrations:
+  #   description: Revert the last migration if successfully run in the current workflow.
+  #   parameters:
+  #     # Add parameter here     
+  #   steps:
+  #     - run:
+  #         name: Revert migrations
+  #         # Add when this will run
+  #         command: |
+  #           # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+  #           SUCCESS = 1
+  #           if(( $SUCCESS==1 )); 
+  #           then
+  #           #  cd ~/project/backend
+  #           #  npm install
+  #           #  Add revert code here. You can find this in the Getting Started section.
+  #             exit 1
+  #           fi
             
 jobs:
   build-frontend:
@@ -213,14 +213,6 @@ jobs:
           command: |
             cd .circleci/ansible
             cat inventory.txt        
-      
-      # - run:
-      #     name: Install dependencies
-      #     command: |
-      #       apk add curl
-      #       apk add openssh-client
-      #       apk add rsync
-      #       apk add --update ansible
 
       - run:
           name: Configure server
@@ -238,22 +230,49 @@ jobs:
   #     - destroy-environment 
       # Here's where you will add some code to rollback on failure      
 
-  # run-migrations:
-  #   docker:
-  #     - image: circleci/node:13.8.0
-  #   steps:
-  #     - checkout
-  #     - run:
-  #         name: Run migrations
-  #         command: |
-  #           # Your code here
-  #           exit 1
-  #     - run:
-  #         name: Send migration results to memstash
-  #         command: |
-  #           # Your code here
-  #           exit 1
-  #    # Here's where you will add some code to rollback on failure      
+  run-migrations:
+    docker:
+      - image: circleci/node:13.8.0
+    steps:
+      - checkout
+      - restore_cache:
+          keys: [backend-build] 
+      
+      - run:
+          name: npm install
+          working_directory: ./backend
+          command: npm install
+
+      - run:
+          name: install dependencies
+          command: |
+            npm install typescript
+            npm --update install python3 npm     
+      
+      - run:
+          name: Run migrations
+          working_directory: ./backend          
+          no_output_timeout: 10m
+          command: |
+            npm run migrations:revert
+            npm run migrations >> migration_output.txt
+            cat migration_output.txt
+      
+      - run:
+          name: Send migration results to memstash
+          working_directory: ./backend
+          command: |
+            if grep -q "has been executed successfully." migrations_output.txt
+            then
+              echo "The Migration Was Successful!!"
+              curl -H "Content-Type: text/plain" -H "token:${CIRCLE_WORKFLOW_ID}" \
+              --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+            else
+              echo "The Migration Was Not Successful"
+              curl -H "Content-Type: text/plain" -H "token:${CIRCLE_WORKFLOW_ID}" \
+              --request PUT --data "0" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+            fi
+     # Here's where you will add some code to rollback on failure      
 
 #   deploy-frontend:
 #     docker:
@@ -369,9 +388,9 @@ workflows:
       #     filters:
       #       branches:
       #         only: [main]
-      - configure-infrastructure
+      # - configure-infrastructure
       #     requires: [deploy-infrastructure]
-      # - run-migrations:
+      - run-migrations
       #     requires: [configure-infrastructure]
       # - deploy-frontend:
       #     requires: [run-migrations]
